# Generated by Django 4.2.3 on 2023-09-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
