# Generated by Django 4.2.3 on 2023-09-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanAcessCustomPagePermission',
        ),
    ]
