# Generated by Django 4.2.3 on 2023-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='titulo',
        ),
    ]
