# Generated by Django 4.2.3 on 2023-10-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_image_image_imagem_rename_title_image_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagem',
            field=models.ImageField(upload_to='images'),
        ),
    ]
