# Generated by Django 4.2.3 on 2023-10-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_image_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
